name: CICD using Maven and Jenkins
on: 
  push:
  workflow_dispatch:
jobs:
  CICDJob:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo on ubuntu server
        uses: actions/checkout@v4
      - name: Install Java and Maven on ubuntu server
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build the source code and generate .war file  
        run: mvn package
      - name: connect to LAB and deploy code on tomcat9
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: '43.205.108.74'
          user: 'labuser'
          pass: 'Nuvelabs123$'
          port: 22
          connect_timeout: 10s
          first_ssh: |
             sudo chmod 777 /var/lib/tomcat9/webapps
          scp: |
             './target/*war' => /var/lib/tomcat9/webapps
          last_ssh: |
             sudo systemctl restart tomcat9
      - name: connect to LAB and deploy code on tomcat9
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: '43.205.108.74'
          user: 'labuser'
          pass: 'Nuvelabs123$'
          port: 22
          connect_timeout: 10s
          first_ssh: |
            sudo curl -l -u admin:111019e42cedd3d2200c07a77c47f473db http://localhost:8080/job/CICD Job/build?token=token22
